// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Shared;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231130104333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("WebApplication1.Shared.Charger", b =>
                {
                    b.Property<int>("ChargerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargerAmpere")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChargerId");

                    b.ToTable("Charger");
                });

            modelBuilder.Entity("WebApplication1.Shared.ChargingDBSchedule", b =>
                {
                    b.Property<int>("ChargingDBScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("TEXT");

                    b.HasKey("ChargingDBScheduleId");

                    b.ToTable("ChargingDBSchedule");
                });

            modelBuilder.Entity("WebApplication1.Shared.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementKWH")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("MeasurementId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("WebApplication1.Shared.Truck", b =>
                {
                    b.Property<int>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatterySizeAh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TruckId");

                    b.ToTable("Truck");
                });
#pragma warning restore 612, 618
        }
    }
}
